version: "3"
services:
  app:
    container_name: app
    build:
      context: .
    command: >
         sh -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    environment:
        - POSTGRES_HOST=db
        - POSTGRES_DB=wwl_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=lazaryshyn
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=wwl_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lazaryshyn
    ports:
      - "5432:5432"


  celery:
    restart: always
    build:
        context: .
    command: celery -A wwl_task.celery worker --loglevel=info
    volumes:
      - .:/app
    container_name: celery
    depends_on:
      - redis
      - app

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf

#
#  celery_worker:
#    container_name: celery_worker
#    build: .
#    command: celery -A wwl_task.celery worker --loglevel=info
#    volumes:
#      - .:/app
#    depends_on:
#      - app
#      - redis
#
#  celery_beat:
#    container_name: celery_beat
#    build: .
#    command: celery -A wwl_task.celery beat --loglevel=info
#    depends_on:
#      - app
#      - redis